### ISSUE TITLE
Extrapoint for Pokelist Exercise

### ISSUE THREAD

**Issue by GeorgeAlexRob** [rstropek-teaching/pokelist-quiz-4bhif-AlexGeorgeRob#1]
Here is the link for the extrapoint: http://pokelist.alexgeorgerob.bplaced.net/
I have also used bootstrapper, so I hope that extrapoint will also be noted.

Greetings,
Alex Rob

**Comment by rstropek** [comment]
@AlexGeorgeRob Thank you for your homework. I tested it, works exactly as expected 👍 Your extra point is secured.

I have not taken a look at your code yet. However, I noticed one thing: With Boostrap, you should always have a [`div class="container"` top node](http://getbootstrap.com/docs/4.0/layout/overview/) in your HTML (there are other options, too, but `container` is the simplest one). With that, your website looks even nicer.

Greetings,
Rainer Stropek.
